# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF3GQlvHRZ2IYA67lhwDuNhAm3IWn64B
"""

from typing import List

def twoSum(nums: List[int], target: int) -> List[int]:
  num_dic = {}

  for i, num in enumerate(nums):
    c = target - num

    if c in num_dic:
      return [num_dic[c], i]


    num_dic[num] = i

  return