# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF3GQlvHRZ2IYA67lhwDuNhAm3IWn64B
"""

from typing import List

def twoSum(nums: List[int], target: int) -> List[int]:

  return